"""Añadido UserMixin y cambiado campos a post

Revision ID: 38cde17dfd1d
Revises: d65905838231
Create Date: 2022-11-18 00:30:52.359326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cde17dfd1d'
down_revision = 'd65905838231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
